project:
  type: website

website:
  title: "Lexun Yu"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog
      - href: about.qmd
        text: About
    right:
      - href: "../../../index.html"
        text: "⬅️ Back to PRPR.ONE"

format:
  html:
    theme:
      light: [cosmo, theme-light.scss]
      dark: [darkly, theme-dark.scss]
    css: styles.css
    toc: true
    respect-user-color-scheme: true
