project:
  type: website
  output-dir: _site

website:
  title: "LY"
  site-url: https://blog.prpr.one
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog
      - href: about.qmd
        text: About
    right:
      - href: "https://prpr.one"
        text: "⬅️ *Back to PRPR.ONE*"
  favicon: images/favicon.ico
  
format:
  html:
    theme:
      light: [cosmo, theme-light.scss]
      dark: [darkly, theme-dark.scss]
    css: styles.css
    toc: true
    respect-user-color-scheme: true
